# Generated by Django 5.1.7 on 2025-03-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=100)),
                ('nome_f', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('cep', models.CharField(max_length=15)),
                ('pais', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
