# Generated by Django 5.1.7 on 2025-03-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_f',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
