# Generated by Django 5.1.7 on 2025-03-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_empresa_complemento_alter_empresa_nome_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contato',
            field=models.CharField(default='', max_length=30),
        ),
    ]
